default_language_version:
    python: python3

exclude: |
    (?x)(
        ^tests/|
        ^docs/|
        ^fugue_sql/_antlr/
    )
repos:
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.14.14
      hooks:
        - id: ruff-check
          args: [--fix]
        - id: ruff-format
