version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-20.04
  tools:
    python: "3.10"
  jobs:
    pre_install:
      - pip install -U pip

sphinx:
  configuration: docs/conf.py

python:
   install:
   - requirements: requirements.txt
