# flake8: noqa
# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys

sys.path.insert(0, os.path.abspath("../"))

from fugue import __version__
import sphinx_rtd_theme

# -- Project information -----------------------------------------------------

project = "Fugue"
version = __version__
copyright = "2022, Fugue Development Team"  # noqa: A001
author = "Han Wang"


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.todo",
    "sphinx.ext.viewcode",
    "sphinx.ext.intersphinx",
    "sphinx.ext.autodoc",
    "sphinx.ext.autodoc.typehints",
    "sphinx_rtd_theme",
    "furo.sphinxext",
]

autodoc_typehints = "description"

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "python"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
# exclude_patterns = ["**/fugue.exceptions.rst",]


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "furo"

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]
html_logo = "_static/logo.svg"
html_theme_options = {
    "logo_only": True,
    "display_version": True,
    "sidebar_hide_name": True,
    "style_nav_header_background": "#264263",
}

master_doc = "index"

intersphinx_mapping = {
    "triad": ("https://triad.readthedocs.io/en/latest", None),
    "tutorial": ("https://fugue-tutorials.readthedocs.io", None),
    "pd": ("https://pandas.pydata.org/docs", None),
    "pa": ("https://arrow.apache.org/docs", None),
    "fs": ("https://docs.pyfilesystem.org/en/latest", None),
    "spark": ("https://spark.apache.org/docs/latest/api/python", None),
    "dask": ("https://docs.dask.org/en/latest", None),
    "ray": ("https://docs.ray.io/en/latest", None),
    "ibis": ("https://ibis-project.org/docs/3.1.0", None),
}
