name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    uses: fugue-project/.common/.github/workflows/pypi-publish.yml@main
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
