# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test Spark < 3

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'docs/**'
      - '**.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'docs/**'
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    # - name: Install spark
    #   run: |
    #     wget https://www.apache.org/dyn/closer.lua/spark/spark-2.4.6/spark-2.4.6-bin-hadoop2.7.tgz -O spark.tgz
    #     mkdir -p /opt/spark
    #     tar -xvf spark.tgz -C /opt/spark --strip-components 1
    #     ls /opt/spark
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install spark
      run: |
        pip install pypandoc==1.7.5
        pip install pyspark==2.4.5
    - name: Install dependencies
      run: |
        make devenvlegacy
    - name: Test
      env:
        ARROW_PRE_0_15_IPC_FORMAT: 1
      run: make testspark
