# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Dask Tests

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - '**.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - '**.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test Dask ${{ matrix.dask-version }} Pandas ${{ matrix.pandas-version }} Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
        dask-version: ["latest", "2025.4.0"]
        pandas-version: ["2.3.3"]

    steps:
    - name: Clone repo
      uses: actions/checkout@v5

    - name: Setup uv ${{ matrix.python-version }}
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: false
        cache-dependency-glob: "pyproject.toml"
        python-version: ${{ matrix.python-version }}

    - name: Update Dask
      if: matrix.dask-version != 'latest'
      run: uv add "dask[dataframe,distributed]==${{ matrix.dask-version }}"

    - name: Update Pandas
      if: matrix.pandas-version != 'latest'
      run: uv add "pandas==${{ matrix.pandas-version }}"

    - name: Install dependencies
      run: |
        make devenv upgrade=1

    - name: Test
      run: make testdask

  test_dask_no_sql:
    name: Dask without SQL Latest
    runs-on: ubuntu-latest

    steps:
    - name: Clone repo
      uses: actions/checkout@v5

    - name: Setup uv 3.11
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: false
        cache-dependency-glob: "pyproject.toml"
        python-version: "3.11"

    - name: Install dependencies
      run: |
        make devenv upgrade=1

    - name: Remove Dask SQL
      run: uv pip uninstall dask-sql duckdb fugue-sql-antlr sqlglot

    - name: Test
      run: make testdask
